name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
    - "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
        - name: macOS
          os: macos-latest

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: geode-sdk/build-geode-mod@main
#      with:
#        combine: true

#  package:
#    name: Package builds
#    runs-on: ubuntu-latest
#    needs: ['build']
#
#    steps:
#    - name: Combine Builds
#      uses: geode-sdk/build-geode-mod@combine
#      id: build
#
#    - name: Upload Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: Build Output
#        path: ${{ steps.build.outputs.build-output }}
